The prep-new-mame and prep-new-mess scripts now support dos2unix instead of just d2u.

diff --git a/src/unix/contrib/porting/prep-new-mame b/src/unix/contrib/porting/prep-new-mame
--- a/src/unix/contrib/porting/prep-new-mame
+++ b/src/unix/contrib/porting/prep-new-mame
@@ -13,15 +13,22 @@
 # Last modified on 11 April 2001.
 
 # Fix the line endings of the included text files, makefiles, and sources.
-if [ -x "`which d2u 2> /dev/null`" ]; then
-  d2u `find . -name "*.txt" -print` 2> /dev/null
-  d2u `find . -name "*.htm" -print` 2> /dev/null
-  d2u `find . -name "*.html" -print` 2> /dev/null
-  d2u `find . -name "*.mak" -print` 2> /dev/null
-  d2u `find . -name "*.ini" -print` 2> /dev/null
-  d2u `find . -name "*.pl" -print` 2> /dev/null
+D2U=
+if [ -x "`which dos2unix 2> /dev/null`" ]; then
+	D2U="dos2unix -kq"
+elif [ -x "`which d2u 2> /dev/null`" ]; then
+	D2U="d2u"
 else
-  echo "Unable to run d2u.  This may cause build problems on some platforms."
+	echo "Unable to run dos2unix or d2u.  This may cause build problems on some platforms."
+fi
+
+if [ -n "$D2U" ]; then
+	$D2U `find . -name "*.txt" -print` 2> /dev/null
+	$D2U `find . -name "*.htm" -print` 2> /dev/null
+	$D2U `find . -name "*.html" -print` 2> /dev/null
+	$D2U `find . -name "*.mak" -print` 2> /dev/null
+	$D2U `find . -name "*.ini" -print` 2> /dev/null
+	$D2U `find . -name "*.pl" -print` 2> /dev/null
 fi
 
 
@@ -30,10 +37,10 @@ fix-comments `find . -name "*.[ch]" -print`
 
 # Copy over the src/unix folder from a previous release.
 if [ -d $1/src/unix ]; then
-  cp -R $1/src/unix src
+	cp -R $1/src/unix src
 else
-  echo "Cannot find src/unix in old xmame directory, exiting..."
-  exit 1
+	echo "Cannot find src/unix in old xmame directory, exiting..."
+	exit 1
 fi
 
 # Make some symlinks.
@@ -44,20 +51,20 @@ ln -s src/unix/install-sh .
 
 # Move the MAME text files to the doc directory.
 if [ -f whatsnew.txt ]; then
-  mv whatsnew.txt doc/mame/
+	mv whatsnew.txt doc/mame/
 fi
 
 if [ -f whatsold.txt ]; then
-  mv whatsold.txt doc/mame/
+	mv whatsold.txt doc/mame/
 fi
 
 if [ -f changed.txt ]; then
-  mv changed.txt doc/mame/
+	mv changed.txt doc/mame/
 fi
 
 if [ -d docs ]; then
-  mv docs/* doc/mame/
-  rm -r docs
+	mv docs/* doc/mame/
+	rm -r docs
 fi
 
 # Rename the MAME makefile and fix its line endings.
diff --git a/src/unix/contrib/porting/prep-new-mess b/src/unix/contrib/porting/prep-new-mess
--- a/src/unix/contrib/porting/prep-new-mess
+++ b/src/unix/contrib/porting/prep-new-mess
@@ -15,26 +15,33 @@
 
 # Copy the MESS files over.
 if [ -d "$1" ]; then
-  cp -R $1/* .
+	cp -R $1/* .
 else
-  echo "Cannot find MESS source directory, exiting..."
-  exit 1
+	echo "Cannot find MESS source directory, exiting..."
+	exit 1
+fi
+
+D2U=
+if [ -x "`which dos2unix 2> /dev/null`" ]; then
+	D2U="dos2unix -kq"
+elif [ -x "`which d2u 2> /dev/null`" ]; then
+	D2U="d2u"
+else
+	echo "Unable to run dos2unix or d2u.  This may cause build problems on some platforms."
 fi
 
 # Fix the line endings of the included text files, makefiles, and sources.
-if [ -x "`which d2u 2> /dev/null`" ]; then
-  d2u `find . -name "*.txt" -print` 2> /dev/null
-  d2u `find . -name "*.htm" -print` 2> /dev/null
-  d2u `find . -name "*.html" -print` 2> /dev/null
-  d2u `find . -name "*.mak" -print` 2> /dev/null
-  d2u `find . -name "*.crc" -print` 2> /dev/null
-  d2u `find . -name "*.vc" -print` 2> /dev/null
-  d2u `find . -name "*.wce" -print` 2> /dev/null
-  d2u makefile.mes 2> /dev/null
-  d2u makefile.vc 2> /dev/null
-  d2u sysinfo.dat 2> /dev/null
-else
-  echo "Unable to run d2u.  This may cause build problems on some platforms."
+if [ -n "$D2U" ]; then
+	$D2U `find . -name "*.txt" -print` 2> /dev/null
+	$D2U `find . -name "*.htm" -print` 2> /dev/null
+	$D2U `find . -name "*.html" -print` 2> /dev/null
+	$D2U `find . -name "*.mak" -print` 2> /dev/null
+	$D2U `find . -name "*.hsi" -print` 2> /dev/null
+	$D2U `find . -name "*.vc" -print` 2> /dev/null
+	$D2U `find . -name "*.wce" -print` 2> /dev/null
+	$D2U makefile.mes 2> /dev/null
+	$D2U makefile.vc 2> /dev/null
+	$D2U sysinfo.dat 2> /dev/null
 fi
 
 # Change // comments to /* */ pairs.  Some C compilers don't like //.  We skip
@@ -47,24 +54,24 @@ rm -rf artwork bios cfg cheat memcard nvram snap software
 
 # Rename some files.
 if [ -f messnew.txt ]; then
-  mv messnew.txt doc/mess/
+	mv messnew.txt doc/mess/
 fi
 
 if [ -f sysinfo.dat ]; then
-  mv sysinfo.dat doc/mess/
+	mv sysinfo.dat doc/mess/
 fi
 
 if [ -f tools/imgtool.txt ]; then
-  mv tools/imgtool.txt doc/mess/
+	mv tools/imgtool.txt doc/mess/
 fi
 
 if [ -f tools/messroms.txt ]; then
-  mv tools/messroms.txt doc/mess/
+	mv tools/messroms.txt doc/mess/
 fi
 
 if [ -d docs ]; then
-  mv docs/* doc/mess/
-  rm -r docs
+	mv docs/* doc/mess/
+	rm -r docs
 fi
 
 # Clean up the files left over from d2u and fix-comments.
